Challange2 json
laridtm/learningCodableJSON pull request #3
Opened 2020-02-15 03:08 UTC by laridtm

Foi criado o projeto para a decodificação de arquivos .json e a apresentação em view controllers.

Link da issue: https://github.com/involvestecnologia/mnc-ios-movies/issues/62

2020-02-15 19:17 UTC, Raafas commented on Challange2JSON/Challange2JSON/CityNameViewCell.swift
> +    func setNameCity(name: String) {
Pq tu criou uma função só pra esse label?
Nao usa nameCity.text?

2020-02-17 14:42 UTC, laridtm commented on Challange2JSON/Challange2JSON/CityNameViewCell.swift
> +    func setNameCity(name: String) {
Pra toda vez que cair na função cellForRowAt ela configurar a célula pelo index do array com o nome das cidades. Sim, usa namecity.text

2020-02-17 15:18 UTC, laridtm commented on Challange2JSON/Challange2JSON/CityNameViewCell.swift
> +    func setNameCity(name: String) {
ja entendi e arrumei kk

2020-02-18 17:41 UTC, Raafas requested changes

2020-02-18 17:41 UTC, Raafas commented on Challange2JSON/Challange2JSON/CityNameViewCell.swift
> +//    func setNameCity(name: String) {
Remove esse código comentado

2020-02-18 17:41 UTC, Raafas commented on Challange2JSON/Challange2JSON/ViewController.swift
> +//        cell?.setNameCity(name: nameCities[indexPath.row])
Remover tbm

2020-02-18 17:41 UTC, Raafas commented on Challange2JSON/Challange2JSON/ViewController.swift
> +//        var index = indexPath.row
tb

2020-02-19 20:52 UTC, merged